modLoader="kotlinforforge"
loaderVersion="[1.4,)"
license="MIT"
issueTrackerURL="https://github.com/vini2003/Blade/issues/"

[[mods]]
modId="blade"
version="2.0.0"
displayName="Blade"
displayURL="https://github.com/vini2003/Blade/"
logoFile="Blade.png"
authors="vini2003"

description='''
A Kotlin-based, DSL-built GUI library for Minecraft.
'''

[[dependencies.blade]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blade]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"

# Note: do not add dependency on 'kotlinforforge' because it won't get loaded as a mod
# This is stupid design but it's what we have

